### ISSUE TITLE
Error: connect timer should not be timing out in connected state

### ISSUE THREAD

**Issue by jtoppine** [jdiamond/MQTT.ts#13]
Since Deno 1.22.3 started having these errors very frequently. Also happens on the latest version 1.23.0

```
Error: connect timer should not be timing out in connected state
    at Client.connectTimedOut (https://deno.land/x/mqtt@0.1.2/client/base_client.ts:949:15)
    at https://deno.land/x/mqtt@0.1.2/client/base_client.ts:938:14
    at https://deno.land/x/mqtt@0.1.2/client/base_client.ts:1108:7
    at Object.action (deno:ext/web/02_timers.js:141:13)
    at handleTimerMacrotask (deno:ext/web/02_timers.js:58:12)

```

**Comment by jdiamond** [comment]
Hi, sorry for not responding earlier. I don't use this project at work so it's hard to find time to spend on it.

I upgraded to the latest version of Deno (1.24.1) and am not seeing this error when connecting to a local Mosquitto broker.

Can you help me understand how are you see it?

Thanks.
